package org.example.stock.services;

import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.stocktracker.model.StockPrice;

@Service
public class StockService {

    @Value("${polygon.io.api.key}")
    private String polygonApiKey;

    public StockPrice getStockPrice(String symbol, Date date) {

        // Check if the passed date is from yesterday or older
        Instant today = Instant.now().truncatedTo(ChronoUnit.DAYS);
        Instant yesterday = today.minus(1, ChronoUnit.DAYS);
        if (date.toInstant().isAfter(yesterday)) {
            throw new IllegalArgumentException("The date must be from yesterday or older.");
        }

        try {
            // Build the URL with the provided symbol and API key
            SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormat.format(date);
            String url = "https://api.polygon.io/v1/open-close/" + symbol + "/" + formattedDate
                    + "?adjusted=true&apiKey=" + polygonApiKey;

            // Create HTTP client and request
            java.net.http.HttpClient client = java.net.http.HttpClient.newHttpClient();
            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder()
                    .uri(java.net.URI.create(url))
                    .GET()
                    .build();

            // Send request and get response
            java.net.http.HttpResponse<String> response = client.send(request,
                    java.net.http.HttpResponse.BodyHandlers.ofString());

            // Parse response (assuming you have a JSON library like Jackson)
            // This is a simplified example
            String jsonResponse = response.body();

            // Use a library like Jackson or org.json to parse the JSON
            org.json.JSONObject json = new org.json.JSONObject(jsonResponse);

            StockPrice stockPrice = new StockPrice();

            // Check if the status is OK
            if ("OK".equals(json.getString("status"))) {
                stockPrice.setSymbol(json.getString("symbol"));
                stockPrice.setOpen(json.getDouble("open"));
                stockPrice.setHigh(json.getDouble("high"));
                stockPrice.setLow(json.getDouble("low"));
                stockPrice.setClose(json.getDouble("close"));
                stockPrice.setVolume(json.getDouble("volume"));
                stockPrice.setAfterHours(json.getDouble("afterHours"));
                stockPrice.setPreMarket(json.getDouble("preMarket"));
                String fromDateStr = json.getString("from");
                Date fromDate = dateFormat.parse(fromDateStr);
                stockPrice.setFrom(fromDate);
            } else {
                throw new RuntimeException("Failed to get stock data: " + jsonResponse);
            }

            return stockPrice;
        } catch (Exception e) {
            throw new RuntimeException("Failed to fetch stock price for " + symbol, e);
        }

    }

    public List<TickerData> getData() {

        var list= List.of(new TickerData("A", "Agilent Technologies Inc."),
                new TickerData("AA", "Alcoa Corporation"),
                new TickerData("AAA", "Alternative Access First Priority CLO Bond ETF"),
                new TickerData("AAAU", "Goldman Sachs Physical Gold ETF Shares"),
                new TickerData("AACB", "Artius II Acquisition Inc. Class A Ordinary Shares"),
                new TickerData("AACBR", "Artius II Acquisition Inc. Rights"),
                new TickerData("AACBU", "Artius II Acquisition Inc. Units"),
                new TickerData("AACG", "ATA Creativity Global American Depositary Shares"),
                new TickerData("AACT", "Ares Acquisition Corporation II"),
                new TickerData("AACT.U",
                        "Ares Acquisition Corporation II Units, each consisting of one Class A ordinary share and one-half of one redeemable warrant"),
                new TickerData("AACT.WS",
                        "Ares Acquisition Corporation II Redeemable Warrants, each whole warrant exercisable for one Class A ordinary share at an exercise price of $11.50"),
                new TickerData("AADR", "AdvisorShares Dorsey Wright ADR ETF"),
                new TickerData("AAL", "American Airlines Group Inc."),
                new TickerData("AAM", "AA Mission Acquisition Corp."),
                new TickerData("AAM.U",
                        "AA Mission Acquisition Corp. Units, each consisting of one Class A Ordinary Share and one-half of one redeemable warrant"),
                new TickerData("AAM.WS",
                        "AA Mission Acquisition Corp. Warrants, each whole warrant entitles the holder to purchase one Class A ordinary share at a price of $11.50 per share"),
                new TickerData("AAME", "Atlantic American Corp"),
                new TickerData("AAMI", "Acadian Asset Management Inc."),
                new TickerData("AAOI", "Applied Optoelectronics, Inc."),
                new TickerData("AAON", "Aaon Inc"),
                new TickerData("AAP", "ADVANCE AUTO PARTS INC"),
                new TickerData("AAPB", "GraniteShares ETF Trust GraniteShares 2x Long AAPL Daily ETF"),
                new TickerData("AAPD", "Direxion Daily AAPL Bear 1X Shares"),
                new TickerData("AAPG", "Ascentage Pharma Group International American Depository Shares"),
                new TickerData("AAPL", "Apple Inc."),
                new TickerData("AAPR", "Innovator Equity Defined Protection ETF - 2 Yr to April 2026"),
                new TickerData("AAPU", "Direxion Shares ETF Trust Direxion Daily AAPL Bull 2X Shares"),
                new TickerData("AAPW", "Roundhill AAPL WeeklyPay ETF"),
                new TickerData("AAPX", "T-Rex 2X Long Apple Daily Target ETF"),
                new TickerData("AAPY", "Kurv Yield Premium Strategy Apple (AAPL) ETF"),
                new TickerData("AARD", "Aardvark Therapeutics, Inc. Common Stock"),
                new TickerData("AAT", "AMERICAN ASSETS TRUST, INC."),
                new TickerData("AAVM", "EA Series Trust Alpha Architect Global Factor Equity ETF"),
                new TickerData("AAXJ", "iShares MSCI All Country Asia ex Japan ETF"),
                new TickerData("AAXJ", "iShares MSCI All Country Asia ex Japan ETF"),
                new TickerData("AAXN", "Axon Enterprise, Inc. Common Stock"),
                new TickerData("AB", "AllianceBernstein Holding, L.P."),
                new TickerData("ABAT", "American Battery Technology Company Common Stock"),
                new TickerData("ABBV", "ABBVIE INC."),
                new TickerData("ABC", "AMERISOURCEBERGEN CORP"),
                new TickerData("ABCB", "Ameris Bancorp"),
                new TickerData("ABCL", "AbCellera Biologics Inc. Common Shares"),
                new TickerData("ABCS", "Alpha Blue Capital US Small-Mid Cap Dynamic ETF"),
                new TickerData("ABEO", "Abeona Therapeutics Inc. Common Stock"),
                new TickerData("ABEQ", "Absolute Select Value ETF"),
                new TickerData("ABEV", "AMBEV S.A."),
                new TickerData("ABFL", "Abacus FCF Leaders ETF"),
                new TickerData("ABG", "Asbury Automotive Group, Inc."),
                new TickerData("ABHY", "Abacus Tactical High Yield ETF"),
                new TickerData("ABIG", "Argent Large Cap ETF"),
                new TickerData("ABL", "Abacus Global Management, Inc. Class A Common Stock"),
                new TickerData("ABLD", "Abacus FCF Real Assets Leaders ETF"),
                new TickerData("ABLG", "Abacus FCF International Leaders ETF"),
                new TickerData("ABLLL", "Abacus Global Management, Inc. 9.875% Fixed Rate Senior Notes due 2028"),
                new TickerData("ABLLW", "Abacus Global Management, Inc. Warrant"),
                new TickerData("ABLS", "Abacus FCF Small Cap Leaders ETF"),
                new TickerData("ABLV", "Able View Global Inc. Class B Ordinary Shares"),
                new TickerData("ABLVW", "Able View Global Inc. Warrant"),
                new TickerData("ABM", "ABM Industries, Inc."),
                new TickerData("ABNB", "Airbnb, Inc. Class A Common Stock"),
                new TickerData("ABNY", "YieldMax ABNB Option Income Strategy ETF"),
                new TickerData("ABOS", "Acumen Pharmaceuticals, Inc. Common Stock"),
                new TickerData("ABOT", "Abacus FCF Innovation Leaders ETF"),
                new TickerData("ABP", "Abpro Holdings, Inc Common Stock"),
                new TickerData("ABPWW", "Abpro Holdings, Inc. Warrant"),
                new TickerData("ABR", "Arbor Realty Trust, Inc."),
                new TickerData("ABRpD",
                        "Arbor Realty Trust, Inc. 6.375% Series D Cumulative Redeemable Preferred Stock, Liquidation Preference $25.00 per Share"),
                new TickerData("ABRpE",
                        "Arbor Realty Trust, Inc. 6.25% Series E Cumulative Redeemable Preferred Stock"),
                new TickerData("ABRpF",
                        "Arbor Realty Trust, Inc. 6.25% Series F Fixed-to-Floating Rate Cumulative Redeemable Preferred Stock, Liquidation Preference $25.00 per share"),
                new TickerData("ABSI", "Absci Corporation Common Stock"),
                new TickerData("ABT", "Abbott Laboratories"),
                new TickerData("ABTS", "Abits Group Inc Ordinary Shares"),
                new TickerData("ABUS", "Arbutus Biopharma Corporation Common Stock"),
                new TickerData("ABVC", "ABVC BioPharma, Inc. Common Stock"),
                new TickerData("ABVE", "Above Food Ingredients Inc. Common Stock"),
                new TickerData("ABVEW", "Above Food Ingredients Inc. Warrants"),
                new TickerData("ABVX", "Abivax SA American Depositary Shares"),
                new TickerData("AC", "Associated Capital Group, Inc."),
                new TickerData("ACA", "Arcosa, Inc. Common Stock"),
                new TickerData("ACAD", "Acadia Pharmaceuticals Inc."),
                new TickerData("ACB", "Aurora Cannabis Inc. Common Shares"),
                new TickerData("ACCO", "Acco Brands Corporation"),
                new TickerData("ACCS", "ACCESS Newswire Inc."),
                new TickerData("ACDC", "ProFrac Holding Corp. Class A Common Stock"),
                new TickerData("ACEL", "Accel Entertainment, Inc."),
                new TickerData("ACES", "ALPS Clean Energy ETF"),
                new TickerData("ACET", "Adicet Bio, Inc. Common Stock"),
                new TickerData("ACGL", "Arch Capital Group Ltd"),
                new TickerData("ACGLN",
                        "Arch Capital Group Ltd. Depositary Shares, each Representing a 1/1,000th Interest in a 4.550% Non-Cumulative Preferred Share, Series G"),
                new TickerData("ACGLO",
                        "Arch Capital Group Ltd. Depositary Shares Each Representing 1/1,000th Interest in a Share of 5.45% Non-Cumulative Preferred Shares, Series F"),
                new TickerData("ACGR", "American Century Large Cap Growth ETF"),
                new TickerData("ACGR", "American Century Large Cap Growth ETF"),
                new TickerData("ACGR", "American Century Large Cap Growth ETF"),
                new TickerData("ACHC", "Acadia Healthcare Company, Inc."),
                new TickerData("ACHR", "Archer Aviation Inc."),
                new TickerData("ACHR.WS",
                        "Archer Aviation Inc. Redeemable Warrants, each whole warrant exercisable for one Class A common stock at an exercise price of $11.50"),
                new TickerData("ACHV", "Achieve Life Sciences, Inc."),
                new TickerData("ACI", "Albertsons Companies, Inc."),
                new TickerData("ACIC", "American Coastal Insurance Corporation Common Stock"),
                new TickerData("ACIM", "SPDR MSCI ACWI IMI ETF"),
                new TickerData("ACIO", "Aptus Collared Investment Opportunity ETF"),
                new TickerData("ACIU", "AC Immune SA"),
                new TickerData("ACIW", "ACI Worldwide, Inc."),
                new TickerData("ACLC", "American Century Large Cap Equity ETF"),
                new TickerData("ACLC", "American Century Large Cap Equity ETF"),
                new TickerData("ACLC", "American Century Large Cap Equity ETF"),
                new TickerData("ACLO", "TCW AAA CLO ETF"),
                new TickerData("ACLS", "Axcelis Technologies Inc"),
                new TickerData("ACLX", "Arcellx, Inc. Common Stock"),
                new TickerData("ACM", "Aecom"),
                new TickerData("ACMR", "ACM Research, Inc. Class A Common Stock"),
                new TickerData("ACN", "Accenture PLC"),
                new TickerData("ACNB", "ACNB Corp"),
                new TickerData("ACNT", "Ascent Industries Co. Common Stock"),
                new TickerData("ACOG", "Alpha Cognition Inc. Common Stock"),
                new TickerData("ACON", "Aclarion, Inc. Common Stock"),
                new TickerData("ACONW", "Aclarion, Inc. Warrant"),
                new TickerData("ACP", "abrdn Income Credit Strategies Fund"),
                new TickerData("ACPpA",
                        "abrdn Income Credit Strategies Fund  5.250% Series A Perpetual Preferred Stock"),
                new TickerData("ACR", "ACRES Commercial Realty Corp."),
                new TickerData("ACRE", "Ares Commercial Real Estate Corporation"),
                new TickerData("ACRS", "Aclaris Therapeutics, Inc."),
                new TickerData("ACRV", "Acrivon Therapeutics, Inc. Common Stock"),
                new TickerData("ACRpC",
                        "ACRES Commercial Realty Corp. 8.625% Fixed-to-Floating Series C Cumulative Redeemable Preferred Stock, par value $0.001 per share"),
                new TickerData("ACRpD",
                        "ACRES Commercial Realty Corp. 7.875% Series D Cumulative Redeemable Preferred Stock"),
                new TickerData("ACSI", "American Customer Satisfaction ETF"),
                new TickerData("ACT", "Enact Holdings, Inc. Common Stock"),
                new TickerData("ACTG", "Acacia Research Corporation"),
                new TickerData("ACTU", "Actuate Therapeutics, Inc. Common stock"),
                new TickerData("ACTV", "LeaderShares Activist Leaders ETF"),
                new TickerData("ACU", "Acme United Corporation"),
                new TickerData("ACV", "Virtus Diversified Income & Convertible Fund"),
                new TickerData("ACVA", "ACV Auctions Inc."),
                new TickerData("ACVF", "American Conservative Values ETF"),
                new TickerData("ACVT", "Advent Convertible Bond ETF"),
                new TickerData("ACWF", "ISHRES TR EDGE MSCI MULTIFACTOR GLOBAL ETF"),
                new TickerData("ACWI", "iShares MSCI ACWI ETF"),
                new TickerData("ACWV", "iShares MSCI Global Min Vol Factor ETF"),
                new TickerData("ACWX", "iShares MSCI ACWI ex US ETF"),
                new TickerData("ACXP", "Acurx Pharmaceuticals, Inc. Common Stock"),
                new TickerData("ADAG", "Adagene Inc. American Depositary Shares"),
                new TickerData("ADAP", "Adaptimmune Therapeutics plc American Depositary Shares"),
                new TickerData("ADBE", "Adobe Inc."),
                new TickerData("ADBG", "Leverage Shares 2X Long ADBE Daily ETF"),
                new TickerData("ADC", "Agree Realty Corporation"),
                new TickerData("ADCT", "ADC Therapeutics SA"),
                new TickerData("ADCpA",
                        "Agree Realty Corporation Depositary Shares, each representing 1/1,000th of a 4.250% Series A Cumulative Redeemable Preferred Stock"),
                new TickerData("ADD", "Color Star Technology Co., Ltd. Class A Ordinary Shares"),
                new TickerData("ADEA", "Adeia Inc. Common Stock"),
                new TickerData("ADFI", "Anfield Dynamic Fixed Income ETF"),
                new TickerData("ADGM", "Adagio Medical Holdings, Inc Common Stock"),
                new TickerData("ADI", "Analog Devices, Inc."),
                new TickerData("ADIL", "Adial Pharmaceuticals, Inc"),
                new TickerData("ADIV", "SmartETFs Asia Pacific Dividend Builder ETF"),
                new TickerData("ADM", "Archer Daniels Midland Company"),
                new TickerData("ADMA", "ADMA Biologics, Inc."),
                new TickerData("ADME", "Aptus Behavioral Momentum ETF"),
                new TickerData("ADN", "Advent Technologies Holdings, Inc. Class A Common Stock"),
                new TickerData("ADNT", "Adient plc Ordinary Shares"),
                new TickerData("ADNWW", "Advent Technologies Holdings, Inc. Warrant"),
                new TickerData("ADP", "Automatic Data Processing"),
                new TickerData("ADPT", "Adaptive Biotechnologies Corporation Common Stock"),
                new TickerData("ADPV", "Adaptiv Select ETF"),
                new TickerData("ADS", "ALLIANCE DATA SYSTEMS CORP"),
                new TickerData("ADSE", "ADS-TEC ENERGY PLC Ordinary Shares"),
                new TickerData("ADSEW", "ADS-TEC ENERGY PLC Warrant"),
                new TickerData("ADSK", "Autodesk Inc"),
                new TickerData("ADT", "ADT Inc."),
                new TickerData("ADTN", "ADTRAN Holdings, Inc. Common Stock"),
                new TickerData("ADTX", "Aditxt, Inc. Common Stock"),
                new TickerData("ADUR", "Aduro Clean Technologies Inc. Common Stock"),
                new TickerData("ADUS", "Addus HomeCare Corp."),
                new TickerData("ADV", "Advantage Solutions Inc. Class A Common Stock"),
                new TickerData("ADVB", "Advanced Biomed Inc. Common Stock"),
                new TickerData("ADVE", "Matthews Asia Dividend Active ETF"),
                new TickerData("ADVM", "Adverum Biotechnologies, Inc. Common Stock"),
                new TickerData("ADVWW", "Advantage Solutions Inc. Warrant"),
                new TickerData("ADX", "Adams Diversified Equity Fund, Inc"),
                new TickerData("ADXN", "Addex Therapeutics Ltd American Depositary Shares"),
                new TickerData("AEE", "Ameren Corporation"),
                new TickerData("AEF", "abrdn Emerging Markets ex-China Fund, Inc."),
                new TickerData("AEFC", "Aegon Funding Company LLC 5.10% Subordinated Notes due 2049"),
                new TickerData("AEG", "Aegon Ltd."),
                new TickerData("AEHL", "Antelope Enterprise Holdings Limited Class A Ordinary Shares"),
                new TickerData("AEHR", "Aehr Test Systems"),
                new TickerData("AEI", "Alset Inc. Common Stock (TX)"),
                new TickerData("AEIS", "Advanced Energy Industries Inc"),
                new TickerData("AEM", "Agnico Eagle Mines Ltd."),
                new TickerData("AEMD", "AETHLON MEDICAL INC"),
                new TickerData("AENT", "Alliance Entertainment Holding Corporation Class A Common Stock"),
                new TickerData("AENTW", "Alliance Entertainment Holding Corporation Warrants"),
                new TickerData("AEO", "American Eagle Outfitters"),
                new TickerData("AEON", "AEON Biopharma, Inc."),
                new TickerData("AEP", "American Electric Power Company, Inc."),
                new TickerData("AER", "Aercap Holdings N.V."),
                new TickerData("AERT", "Aeries Technology, Inc. Class A Ordinary Share"),
                new TickerData("AERTW", "Aeries Technology, Inc. Warrant"),
                new TickerData("AES", "AES Corporation"),
                new TickerData("AESI", "Atlas Energy Solutions Inc."),
                new TickerData("AESR", "Anfield U.S. Equity Sector Rotation ETF"),
                new TickerData("AETH", "Bitwise Trendwise Ether and Treasuries Rotation Strategy ETF"),
                new TickerData("AEVA", "Aeva Technologies, Inc."),
                new TickerData("AEVAW", "Aeva Technologies, Inc. Warrants"),
                new TickerData("AEYE", "AudioEye, Inc. Common Stock"),
                new TickerData("AFB", "Alliance National Municipal Income Fund, Inc."),
                new TickerData("AFBI", "Affinity Bancshares, Inc. Common Stock (MD)"),
                new TickerData("AFCG", "Advanced Flower Capital Inc. Common Stock"),
                new TickerData("AFG", "American Financial Group, Inc."),
                new TickerData("AFGB", "American Financial Group, Inc. 5.875% Subordinated Debentures due 2059"),
                new TickerData("AFGC", "American Financial Group, Inc. 5.125% Subordinated Debentures due 2059"),
                new TickerData("AFGD", "American Financial Group, Inc. 5.625% Subordinated Debentures due 2060"),
                new TickerData("AFGE", "American Financial Group, Inc. 4.500% Subordinated Debentures due 2060"),
                new TickerData("AFIF", "Anfield Universal Fixed Income ETF"),
                new TickerData("AFIX", "Allspring Broad Market Core Bond ETF"),
                new TickerData("AFJK", "Aimei Health Technology Co., Ltd Ordinary Share"),
                new TickerData("AFJKR", "Aimei Health Technology Co., Ltd Right"),
                new TickerData("AFJKU", "Aimei Health Technology Co., Ltd Unit"),
                new TickerData("AFK", "VanEck Africa Index ETF"),
                new TickerData("AFL", "Aflac Inc."),
                new TickerData("AFLG", "First Trust Active Factor Large Cap ETF"),
                new TickerData("AFMC", "First Trust Active Factor Mid Cap ETF"),
                new TickerData("AFMD", "Affimed N.V."),
                new TickerData("AFRI", "Forafric Global PLC Ordinary Shares"),
                new TickerData("AFRIW", "Forafric Global PLC Warrants"),
                new TickerData("AFRM", "Affirm Holdings, Inc. Class A Common Stock"),
                new TickerData("AFSC", "abrdn Focused U.S. Small Cap Active ETF"),
                new TickerData("AFSM", "First Trust Active Factor Small Cap ETF"),
                new TickerData("AFYA", "Afya Limited Class A Common Shares"),
                new TickerData("AG", "FIRST MAJESTIC SILVER CORP"),
                new TickerData("AGAE", "Allied Gaming & Entertainment Inc. Common Stock"),
                new TickerData("AGCO", "AGCO Corporation"),
                new TickerData("AGD", "abrdn Global Dynamic Dividend Fund"),
                new TickerData("AGEM", "abrdn Emerging Markets Dividend Active ETF"),
                new TickerData("AGEN", "Agenus Inc."),
                new TickerData("AGFY", "Agrify Corporation Common Stock"),
                new TickerData("AGG", "iShares Core U.S. Aggregate Bond ETF"),
                new TickerData("AGGA", "Astoria Dynamic Core US Fixed Income ETF"),
                new TickerData("AGGH", "Simplify Aggregate Bond ETF"),
                new TickerData("AGGS", "Harbor Disciplined Bond ETF"),
                new TickerData("AGGY", "WisdomTree Yield Enhanced U.S. Aggregate Bond Fund"),
                new TickerData("AGH", "Aureus Greenway Holdings Inc. Common Stock"),
                new TickerData("AGI", "Alamos Gold Inc. Class A Common Shares"),
                new TickerData("AGIH", "iShares Inflation Hedged U.S. Aggregate Bond ETF"),
                new TickerData("AGIO", "Agios Pharmaceuticals, Inc."),
                new TickerData("AGIX", "KraneShares Artificial Intelligence ETF"),
                new TickerData("AGL", "agilon health, inc."),
                new TickerData("AGM", "Federal Agricultural Mortgage Corporation"),
                new TickerData("AGM.A", "Federal Agricultural Mortgage Corporation Class A Voting"),
                new TickerData("AGMH", "AGM Group Holdings Inc. Class A Ordinary Shares"),
                new TickerData("AGMI", "Themes Silver Miners ETF"),
                new TickerData("AGMpD",
                        "Federal Agricultural Mortgage Corporation 5.700% Non-Cumulative Preferred Stock, Series D"),
                new TickerData("AGMpE",
                        "Federal Agricultural Mortgage Corporation 5.750% Non-Cumulative Preferred Stock, Series E"),
                new TickerData("AGMpF",
                        "Federal Agricultural Mortgage Corporation 5.250% Non-Cumulative Preferred Stock, Series F"),
                new TickerData("AGMpG",
                        "Federal Agricultural Mortgage Corporation 4.875% Non-Cumulative Preferred Stock, Series G"),
                new TickerData("AGNC", "AGNC Investment Corp. Common Stock"),
                new TickerData("AGNCL",
                        "AGNC Investment Corp. Depositary Shares Each Representing a 1/1,000th Interest in a Share of 7.75% Series G Fixed-Rate Reset Cumulative Redeemable Preferred Stock"),
                new TickerData("AGNCM",
                        "AGNC Investment Corp. Depositary Shares rep 6.875% Series D Fixed-to-Floating Cumulative Redeemable Preferred Stock"),
                new TickerData("AGNCN",
                        "AGNC Investment Corp. Depositary Shares Each Representing a 1/1,000th Interest in a Share of 7 percent Series C Fixed-To-Floating Rate Cumulative Redeemable Preferred Stock"),
                new TickerData("AGNCO",
                        "AGNC Investment Corp. Depositary Shares, each representing a 1/1,000th interest in a share of 6.50% Series E Fixed-to-Floating Cumulative Redeemable Preferred Stock"),
                new TickerData("AGNCP",
                        "AGNC Investment Corp. Depositary Shares Each Representing a 1/1,000th Interest in a Share of 6.125% Series F Fixed-to-Floating Rate Cumulative Redeemable Preferred Stock"),
                new TickerData("AGNG", "Global X Funds Global X Aging Population ETF"),
                new TickerData("AGNG", "Global X Funds Global X Aging Population ETF"),
                new TickerData("AGO", "Assured Guaranty, LTD"),
                new TickerData("AGOX", "Adaptive Alpha Opportunities ETF"),
                new TickerData("AGQ", "ProShares Ultra Silver"),
                new TickerData("AGQI", "First Trust Active Global Quality Income ETF"),
                new TickerData("AGRH", "iShares Interest Rate Hedged U.S. Aggregate Bond ETF"),
                new TickerData("AGRI", "AgriFORCE Growing Systems Ltd. Common Shares"),
                new TickerData("AGRO", "ADECOAGRO S.A."),
                new TickerData("AGRW", "Allspring LT Large Growth ETF"),
                new TickerData("AGS", "PlayAGS, Inc."),
                new TickerData("AGX", "Argan, Inc"),
                new TickerData("AGYS", "Agilysys, Inc. Common Stock (DE)"),
                new TickerData("AGZ", "iShares Agency Bond ETF"),
                new TickerData("AGZD", "WisdomTree Trust WisdomTree Interest Rate Hedged U.S. Aggregate Bond Fund"),
                new TickerData("AHCO", "AdaptHealth Corp. Common Stock"),
                new TickerData("AHG", "Akso Health Group ADS"),
                new TickerData("AHH", "Armada Hoffler Properties, Inc."),
                new TickerData("AHHpA",
                        "Armada Hoffler Properties, Inc. 6.75% Series A Cumulative Redeemable Perpetual Preferred Stock"),
                new TickerData("AHL", "Aspen Insurance Holdings Limited"),
                new TickerData("AHLT", "American Beacon AHL Trend ETF"),
                new TickerData("AHLpD",
                        "Aspen Insurance Holdings Limited 5.625% Perpetual Non-Cumulative Preference Shares"),
                new TickerData("AHLpE",
                        "Aspen Insurance Holdings Limited Depositary Shares, each representing a 1/1000th interest in a share of 5.625% Perpetual Non-Cumulative Preference Shares"),
                new TickerData("AHLpF",
                        "Aspen Insurance Holdings Limited Depositary Shares, each representing a 1/1,000th Interest in a 7.00% Perpetual Non-Cumulative Preference Share"),
                new TickerData("AHR", "American Healthcare REIT, Inc."),
                new TickerData("AHS", "AMN HEALTHCARE SERVICES"),
                new TickerData("AHT", "Ashford Hospitality Trust, Inc."),
                new TickerData("AHTpD", "Ashford Hospitality Trust, Inc. 8.45% Series D"),
                new TickerData("AHTpF", "Ashford Hospitality Trust, Inc."),
                new TickerData("AHTpG", "Ashford Hospitality Trust, Inc   7.375% Series G Cumulative Preferred Stock"),
                new TickerData("AHTpH",
                        "Ashford Hospitality Trust, Inc. 7.50 Percent Series H Cumulative Preferred Stock"),
                new TickerData("AHTpI", "Ashford Hospitality Trust, Inc. 7.50% Series I Cumulative Preferred Stock"),
                new TickerData("AHYB", "American Century Select High Yield ETF"),
                new TickerData("AI", "C3.ai, Inc."),
                new TickerData("AIA", "iShares Asia 50 ETF"),
                new TickerData("AIBD", "Direxion Daily AI and Big Data Bear 2X Shares"),
                new TickerData("AIBU", "Direxion Daily AI and Big Data Bull 2X Shares"),
                new TickerData("AIEQ", "Amplify AI Powered Equity ETF"),
                new TickerData("AIFD", "TCW Artificial Intelligence ETF"),
                new TickerData("AIFE", "Aifeex Nexus Acquisition Corporation Class A Ordinary Shares"),
                new TickerData("AIFER", "Aifeex Nexus Acquisition Corporation Right"),
                new TickerData("AIFER", "Aifeex Nexus Acquisition Corporation Right"),
                new TickerData("AIFEU", "Aifeex Nexus Acquisition Corporation Unit"),
                new TickerData("AIFF", "Firefly Neuroscience, Inc. Common Stock"),
                new TickerData("AIFU", "AIFU Inc. American Depositary Shares"),
                new TickerData("AIG", "American International Group, Inc."),
                new TickerData("AIHS", "Senmiao Technology Limited Common Stock"),
                new TickerData("AII", "American Integrity Insurance Group, Inc."),
                new TickerData("AIMD", "Ainos, Inc. Common Stock"),
                new TickerData("AIMDW", "Ainos, Inc. Warrants"),
                new TickerData("AIN", "Albany International Corp Class A"),
                new TickerData("AINP", "Allspring Income Plus ETF"),
                new TickerData("AIO", "Virtus Artificial Intelligence & Technology Opportunities Fund"),
                new TickerData("AIOT", "PowerFleet, Inc. Common Stock"),
                new TickerData("AIP", "Arteris, Inc. Common Stock"),
                new TickerData("AIPI", "REX AI Equity Premium Income ETF"),
                new TickerData("AIQ", "Global X Funds Global X Artificial Intelligence & Technology ETF"),
                new TickerData("AIR", "AAR Corp."),
                new TickerData("AIRE", "reAlpha Tech Corp. Common Stock"),
                new TickerData("AIRG", "Airgain, Inc. Common Stock"),
                new TickerData("AIRI", "Air Industries Group"),
                new TickerData("AIRJ", "AirJoule Technologies Corporation Class A Common Stock"),
                new TickerData("AIRJW", "AirJoule Technologies Corporation Warrant"),
                new TickerData("AIRL", "Themes Airlines ETF"),
                new TickerData("AIRR", "First Trust RBA American Industrial Renaissance ETF"),
                new TickerData("AIRS", "AirSculpt Technologies, Inc. Common Stock"),
                new TickerData("AIRT", "Air T Inc"),
                new TickerData("AIRTP", "Air T, Inc. Air T Funding Alpha Income Trust Preferred Securities"),
                new TickerData("AIS", "VistaShares Artificial Intelligence Supercycle ETF"),
                new TickerData("AISP", "Airship AI Holdings, Inc. Class A Common Stock"),
                new TickerData("AISPW", "Airship AI Holdings, Inc. Warrants"),
                new TickerData("AIT", "Applied Industrial Technologies, Inc."),
                new TickerData("AIV", "Apartment Investment and Management Company"),
                new TickerData("AIVC", "Amplify Bloomberg AI Value Chain ETF"),
                new TickerData("AIVI", "WisdomTree International AI Enhanced Value Fund"),
                new TickerData("AIVI", "WisdomTree International AI Enhanced Value Fund"),
                new TickerData("AIVL", "WisdomTree U.S. AI Enhanced Value Fund"),
                new TickerData("AIXI", "XIAO-I Corporation American Depositary Shares"),
                new TickerData("AIYY", "YieldMax AI Option Income Strategy ETF"),
                new TickerData("AIZ", "Assurant, Inc."),
                new TickerData("AIZN", "Assurant, Inc. 5.25% Subordinated Notes due 2061"),
                new TickerData("AJAN", "Innovator Equity Defined Protection ETF - 2 Yr to January 2026"),
                new TickerData("AJG", "Arthur J. Gallagher & Co."),
                new TickerData("AJUL", "Innovator Equity Defined Protection ETF - 2 Yr to July 2026"),
                new TickerData("AKA", "a.k.a. Brands Holding Corp."),
                new TickerData("AKAM", "Akamai Technologies Inc"),
                new TickerData("AKAN", "Akanda Corp. Common Shares"),
                new TickerData("AKBA", "Akebia Therapeutics, Inc."),
                new TickerData("AKO.A", "Embotelladora Andina S.A. Series A"),
                new TickerData("AKO.B", "Embotelladora Andina S.A. Series B"),
                new TickerData("AKR", "Acadia Realty Trust"),
                new TickerData("AKRO", "Akero Therapeutics, Inc. Common Stock"),
                new TickerData("AKTX", "Akari Therapeutics plc ADR (0.01 USD)"),
                new TickerData("AKYA", "Akoya BioSciences, Inc. Common Stock"),
                new TickerData("AL", "Air Lease Corporation"),
                new TickerData("ALAB", "Astera Labs, Inc. Common Stock"),
                new TickerData("ALAI", "Alger AI Enablers & Adopters ETF"),
                new TickerData("ALAR", "Alarum Technologies Ltd. American Depositary Share"),
                new TickerData("ALB", "Albemarle Corporation"),
                new TickerData("ALBT", "Avalon GloboCare Corp. Common Stock"),
                new TickerData("ALBpA",
                        "Albemarle Corporation Depositary Shares each representing a 1/20th interest in a share of 7.25% Series A Mandatory Convertible Preferred Stock"),
                new TickerData("ALC", "Alcon Inc. Ordinary Shares"),
                new TickerData("ALCO", "Alico Inc"),
                new TickerData("ALCY", "Alchemy Investments Acquisition Corp 1 Class A Ordinary Shares"),
                new TickerData("ALCYU", "Alchemy Investments Acquisition Corp 1 Units"),
                new TickerData("ALCYW", "Alchemy Investments Acquisition Corp 1 Warrants"),
                new TickerData("ALDF", "Aldel Financial II Inc. Class A Ordinary Shares"),
                new TickerData("ALDFU", "Aldel Financial II Inc. Units"),
                new TickerData("ALDFW", "Aldel Financial II Inc. Warrants"),
                new TickerData("ALDX", "Aldeyra Therapeutics, Inc."),
                new TickerData("ALE", "ALLETE, Inc."),
                new TickerData("ALEC", "Alector, Inc. Common Stock"),
                new TickerData("ALEX", "Alexander & Baldwin, Inc."),
                new TickerData("ALF", "Centurion Acquisition Corp. Class A Ordinary Shares"),
                new TickerData("ALFUU", "Centurion Acquisition Corp. Unit"),
                new TickerData("ALFUW", "Centurion Acquisition Corp. Warrant"),
                new TickerData("ALG", "Alamo Group, Inc."),
                new TickerData("ALGM", "Allegro MicroSystems, Inc. Common Stock"),
                new TickerData("ALGN", "Align Technology Inc"),
                new TickerData("ALGS", "Aligos Therapeutics, Inc. Common Stock"),
                new TickerData("ALGT", "Allegiant Travel Company"),
                new TickerData("ALHC", "Alignment Healthcare, Inc. Common Stock"),
                new TickerData("ALIL", "Argent Focused Small Cap ETF"),
                new TickerData("ALIT", "Alight, Inc."),
                new TickerData("ALK", "Alaska Air Group, Inc."),
                new TickerData("ALKS", "Alkermes Inc. plc"),
                new TickerData("ALKT", "Alkami Technology, Inc. Common Stock"),
                new TickerData("ALL", "The Allstate Corporation"),
                new TickerData("ALLE", "Allegion Public Limited Company"),
                new TickerData("ALLO", "Allogene Therapeutics, Inc. Common Stock"),
                new TickerData("ALLR", "Allarity Therapeutics, Inc. Common Stock"),
                new TickerData("ALLT", "Allot Ltd. Ordinary Shares"),
                new TickerData("ALLW", "SPDR Bridgewater All Weather ETF"),
                new TickerData("ALLY", "Ally Financial Inc."),
                new TickerData("ALLpB",
                        "The Allstate Corporation 5.100%  Fixed-To-Floating Rate Subordinated Debentures due 2053"),
                new TickerData("ALLpH", "The Allstate Corporation"),
                new TickerData("ALLpI", "The Allstate Corporation"),
                new TickerData("ALLpJ",
                        "The Allstate Corporation Depositary Shares each representing a 1/1,000th interest in a share of Fixed Rate Noncumulative Perpetual Preferred Stock, Series J"),
                new TickerData("ALMS", "Alumis Inc. Common Stock"),
                new TickerData("ALMU", "Aeluma, Inc. Common Stock"),
                new TickerData("ALNT", "Allient Inc. Common Stock"),
                new TickerData("ALNY", "Alnylam Pharmaceuticals, Inc."),
                new TickerData("ALOT", "AstroNova, Inc. Common Stock"),
                new TickerData("ALRM", "Alarm.com Holdings, Inc."),
                new TickerData("ALRS", "Alerus Financial Corporation Common Stock"),
                new TickerData("ALSN", "ALLISON TRANSMISSION HOLDINGS, INC."),
                new TickerData("ALT", "Altimmune, Inc. Common Stock"),
                new TickerData("ALTG", "Alta Equipment Group Inc."),
                new TickerData("ALTGpA",
                        "Alta Equipment Group Inc. Depositary Shares (each representing 1/1000th in a share of 10% Series A Cumulative Perpetual Preferred Stock)"),
                new TickerData("ALTI", "AlTi Global, Inc. Class A Common Stock"),
                new TickerData("ALTL", "Pacer Lunt Large Cap Alternator ETF"),
                new TickerData("ALTO", "Alto Ingredients, Inc. Common Stock"),
                new TickerData("ALTS", "ALT5 Sigma Corporation Common Stock"),
                new TickerData("ALTY", "Global X Funds Global X Alternative Income ETF"),
                new TickerData("ALUR", "Allurion Technologies, Inc."),
                new TickerData("ALUR.WS",
                        "Allurion Technologies, Inc. Warrants, each whole warrant exercisable to purchase 0.056818 shares of common stock at an exercise price of $202.50 per share of common stock"),
                new TickerData("ALV", "Autoliv, Inc."),
                new TickerData("ALVO", "Alvotech Ordinary Shares"),
                new TickerData("ALVOW", "Alvotech Warrant"),
                new TickerData("ALX", "Alexander's Inc."),
                new TickerData("ALXO", "ALX Oncology Holdings Inc. Common Stock"),
                new TickerData("ALZN", "Alzamend Neuro, Inc. Common Stock"),
                new TickerData("AM", "Antero Midstream Corporation Common Stock"),
                new TickerData("AMAL", "Amalgamated Financial Corp. Common Stock (DE)"),
                new TickerData("AMAT", "Applied Materials Inc"),
                new TickerData("AMAX", "Adaptive Hedged Multi-Asset Income ETF"),
                new TickerData("AMBA", "Ambarella, Inc. Ordinary Shares"),
                new TickerData("AMBC", "Ambac Financial Group, Inc."),
                new TickerData("AMBI", "Ambipar Emergency Response"),
                new TickerData("AMBI.WS",
                        "Ambipar Emergency Response Warrants to purchase Class A ordinary shares, each whole warrant exercisable for one Class A ordinary share at an exercise price of $11.50 per share"),
                new TickerData("AMBO",
                        "Ambow Education Holding Ltd. American Depository Shares (each representing twenty (20) Class A Ordinary Shares)"),
                new TickerData("AMBP", "Ardagh Metal Packaging S.A."),
                new TickerData("AMBP.WS",
                        "Ardagh Metal Packaging S.A. Warrants, each exercisable for one Share at an exercise price of $11.50 per share"),
                new TickerData("AMBR", "Amber International Holding Limited American Depositary Shares"),
                new TickerData("AMC", "AMC ENTERTAINMENT HOLDINGS, INC."),
                new TickerData("AMCR", "Amcor plc Ordinary Shares"),
                new TickerData("AMCX", "AMC Networks Inc. Class A"),
                new TickerData("AMD", "Advanced Micro Devices"),
                new TickerData("AMDD", "Direxion Daily AMD Bear 1X Shares"),
                new TickerData("AMDG", "Leverage Shares 2X Long AMD Daily ETF"),
                new TickerData("AMDL", "GraniteShares 2x Long AMD Daily ETF"),
                new TickerData("AMDS", "GraniteShares 1x Short AMD Daily ETF"),
                new TickerData("AMDY", "YieldMax AMD Option Income Strategy ETF"),
                new TickerData("AME", "Ametek, Inc."),
                new TickerData("AMED", "Amedisys Inc"),
                new TickerData("AMG", "Affiliated Managers Group"),
                new TickerData("AMGN", "Amgen Inc"),
                new TickerData("AMH", "AMERICAN HOMES 4 RENT"),
                new TickerData("AMHpG",
                        "American Homes 4 Rent Series G cumulative redeemable perpetual preferred shares of beneficial interest"),
                new TickerData("AMHpH",
                        "American Homes 4 Rent Series H cumulative redeemable perpetual Preferred Shares of Beneficial Interest"),
                new TickerData("AMID", "Argent Mid Cap ETF"),
                new TickerData("AMIX", "Autonomix Medical, Inc. Common Stock"),
                new TickerData("AMJB", "Alerian MLP Index ETNs due January 28 2044"),
                new TickerData("AMKR", "Amkor Technology Inc"),
                new TickerData("AMLP", "Alerian MLP ETF"),
                new TickerData("AMLX", "Amylyx Pharmaceuticals, Inc. Common Stock"),
                new TickerData("AMN", "AMN Healthcare Services"),
                new TickerData("AMOD", "Alpha Modus Holdings, Inc. Class A Common Stock"),
                new TickerData("AMODW", "Alpha Modus Holdings, Inc. Warrant"),
                new TickerData("AMOM", "Qraft AI-Enhanced US Large Cap Momentum ETF"),
                new TickerData("AMP", "Ameriprise Financial, Inc."),
                new TickerData("AMPG", "AMPLITECH GROUP INC. COM"),
                new TickerData("AMPGW", "Amplitech Group, Inc. Warrants"),
                new TickerData("AMPH", "Amphastar Pharmaceuticals, Inc."),
                new TickerData("AMPL", "Amplitude, Inc. Class A Common Stock"),
                new TickerData("AMPX", "Amprius Technologies, Inc."),
                new TickerData("AMPX.WS",
                        "Amprius Technologies, Inc. Warrants to purchase one share of Common Stock at an exercise price of $11.50 per share"),
                new TickerData("AMPY", "Amplify Energy Corp."),
                new TickerData("AMR", "Alpha Metallurgical Resources, Inc."),
                new TickerData("AMRC", "Ameresco, Inc."),
                new TickerData("AMRK", "A-Mark Precious Metals, Inc."),
                new TickerData("AMRN", "Amarin Corp Plc"),
                new TickerData("AMRX", "Amneal Pharmaceuticals, Inc. Class A Common Stock"),
                new TickerData("AMS", "American Shared Hospital Services"),
                new TickerData("AMSC", "American Superconductor Corp"),
                new TickerData("AMSF", "AMERISAFE, Inc."),
                new TickerData("AMST", "Amesite Inc."),
                new TickerData("AMT", "American Tower Corporation"),
                new TickerData("AMTB", "Amerant Bancorp Inc."),
                new TickerData("AMTD",
                        "AMTD IDEA Group American Depositary Shares, each representing six (6) Class A Ordinary Shares"),
                new TickerData("AMTM", "Amentum Holdings, Inc."),
                new TickerData("AMTX", "Aemetis, Inc. (DE) Common Stock"),
                new TickerData("AMUB", "ETRACS Alerian MLP Index ETN Series B due July 18, 2042"),
                new TickerData("AMUU", "Direxion Daily AMD Bull 2X Shares"),
                new TickerData("AMWD", "American Woodmark Corp"),
                new TickerData("AMWL", "American Well Corporation"),
                new TickerData("AMX",
                        "America Movil S.A.B de C.V American Depositary Shares (each representing the right to receive twenty (20) Series B Shares)"),
                new TickerData("AMZA", "InfraCap MLP ETF"),
                new TickerData("AMZD", "Direxion Daily AMZN Bear 1X Shares"),
                new TickerData("AMZE", "Amaze Holdings, Inc."),
                new TickerData("AMZN", "Amazon.Com Inc"),
                new TickerData("AMZP", "Kurv Yield Premium Strategy Amazon (AMZN) ETF"),
                new TickerData("AMZU", "Direxion Shares ETF Trust Direxion Daily AMZN Bull 2X Shares"),
                new TickerData("AMZY", "YieldMax AMZN Option Income Strategy ETF"),
                new TickerData("AMZZ", "GraniteShares 2x Long AMZN Daily ETF"),
                new TickerData("AN", "AutoNation, Inc."),
                new TickerData("ANAB", "AnaptysBio, Inc. Common Stock"),
                new TickerData("ANDE", "Andersons Inc/The"),
                new TickerData("ANEB", "Anebulo Pharmaceuticals, Inc. Common Stock"),
                new TickerData("ANET", "Arista Networks"),
                new TickerData("ANEW", "ProShares MSCI Transformational Changes ETF"),
                new TickerData("ANF", "Abercrombie & Fitch Co."),
                new TickerData("ANGH", "Anghami Inc. Ordinary Shares"),
                new TickerData("ANGHW", "Anghami Inc. Warrants"),
                new TickerData("ANGI", "Angi Inc. Class A Common Stock"),
                new TickerData("ANGL", "VanEck Fallen Angel High Yield Bond ETF"),
                new TickerData("ANGL", "VanEck Fallen Angel High Yield Bond ETF"),
                new TickerData("ANGO", "AngioDynamics, Inc."),
                new TickerData("ANGpB",
                        "American National Group Inc.  Depositary Shares, each representing a 1/1, 000th interest in a share of 6.625% Fixed-Rate Reset Non-Cumulative Preferred Stock, Series B"),
                new TickerData("ANGpD",
                        "American National Group Inc. Depositary Shares, each representing a 1/1000th interest in a share of 7.375% Fixed-Rate Non-Cumulative Preferred Stock, Series D"),
                new TickerData("ANIK", "Anika Therapeutics Inc"),
                new TickerData("ANIP", "ANI Pharmaceuticals, Inc."),
                new TickerData("ANIX", "Anixa Biosciences, Inc."),
                new TickerData("ANL", "Adlai Nortye Ltd. American Depositary Shares"),
                new TickerData("ANNA", "AleAnna, Inc. Class A Common Stock"),
                new TickerData("ANNAW", "AleAnna, Inc. Warrant"),
                new TickerData("ANNX", "Annexon, Inc. Common Stock"),
                new TickerData("ANRO", "Alto Neuroscience Inc."),
                new TickerData("ANSC",
                        "Agriculture & Natural Solutions Acquisition Corporation Class A Ordinary Shares"),
                new TickerData("ANSCU", "Agriculture & Natural Solutions Acquisition Corporation Unit"),
                new TickerData("ANSCW", "Agriculture & Natural Solutions Acquisition Corporation Warrant"),
                new TickerData("ANSS", "Ansys Inc"),
                new TickerData("ANTA", "Antalpha Platform Holding Company ordinary shares"),
                new TickerData("ANTE", "AirNet Technology Inc. American Depositary Shares"),
                new TickerData("ANTM", "ANTHEM INC COM STK (IN)"),
                new TickerData("ANTX", "AN2 Therapeutics, Inc. Common Stock"),
                new TickerData("ANVS", "Annovis Bio, Inc."),
                new TickerData("ANY", "Sphere 3D Corp. Common Shares"),
                new TickerData("AOA", "iShares Core Aggressive Allocation ETF"),
                new TickerData("AOA", "iShares Core 80/20 Aggressive Allocation ETF"),
                new TickerData("AOCT", "Innovator Equity Defined Protection ETF - 2 Yr to October 2026"),
                new TickerData("AOD", "abrdn Total Dynamic Dividend Fund"),
                new TickerData("AOHY", "Angel Oak High Yield  Opportunities ETF"),
                new TickerData("AOK", "iShares Core Conservative Allocation ETF"),
                new TickerData("AOK", "iShares Core 30/70 Conservative Allocation ETF"),
                new TickerData("AOM", "iShares Core 40/60 Moderate Allocation ETF"),
                new TickerData("AOMN", "Angel Oak Mortgage REIT, Inc. 9.500% Senior Notes due 2029"),
                new TickerData("AOMR", "Angel Oak Mortgage REIT, Inc."),
                new TickerData("AON", "Aon plc Class A"),
                new TickerData("AOR", "iShares Core Growth Allocation ETF"),
                new TickerData("AOR", "iShares Core 60/40 Balanced Allocation ETF"),
                new TickerData("AORT", "Artivion, Inc."),
                new TickerData("AOS", "A.O. Smith Corporation"),
                new TickerData("AOSL", "Alpha and Omega Semiconductor Limited"),
                new TickerData("AOTG", "AOT Growth and Innovation ETF"),
                new TickerData("AOUT", "American Outdoor Brands, Inc. Common Stock"),
                new TickerData("AP", "Ampco-Pittsburgh Corp."),
                new TickerData("AP.W",
                        "Ampco-Pittsburgh Corporation Series A Warrants to purchase Shares of common stock"),
                new TickerData("APA", "APA Corporation Common Stock"),
                new TickerData("APAM", "ARTISAN PARTNERS ASSET MANAGEMENT INC."),
                new TickerData("APCB", "ActivePassive Core Bond ETF"),
                new TickerData("APCX", "AppTech Payments Corp. Common Stock"),
                new TickerData("APCXW", "AppTech Payments Corp. Warrant"),
                new TickerData("APD", "Air Products & Chemicals, Inc."),
                new TickerData("APDN", "Applied DNA Sciences, Inc."),
                new TickerData("APED", "STKd 100% MSTR & 100% COIN ETF"),
                new TickerData("APEI", "American Public Education, Inc."),
                new TickerData("APG", "APi Group Corporation"),
                new TickerData("APGE", "Apogee Therapeutics, Inc. Common Stock"),
                new TickerData("APH", "Amphenol Corporation"),
                new TickerData("API", "Agora, Inc. American Depositary Shares"),
                new TickerData("APIE", "ActivePassive International Equity ETF"),
                new TickerData("APLD", "Applied Digital Corporation Common Stock"),
                new TickerData("APLE", "Apple Hospitality REIT, Inc."),
                new TickerData("APLM", "Apollomics Inc. Class A Ordinary Shares"),
                new TickerData("APLMW", "Apollomics Inc. Warrant"),
                new TickerData("APLS", "Apellis Pharmaceuticals, Inc. Common Stock"),
                new TickerData("APLT", "Applied Therapeutics, Inc. Common Stock"),
                new TickerData("APLU", "Allspring Core Plus ETF"),
                new TickerData("APLY", "YieldMax AAPL Option Income Strategy ETF"),
                new TickerData("APM", "Aptorum Group Limited Class A Ordinary Shares"),
                new TickerData("APMU", "ActivePassive Intermediate Municipal Bond ETF"),
                new TickerData("APO", "Apollo Global Management, Inc."),
                new TickerData("APOC", "Innovator Equity Defined Protection ETF - 6mo Apr/Oct"),
                new TickerData("APOG", "Apogee Enterprises Inc"),
                new TickerData("APOS",
                        "Apollo Global Management, Inc. 7.625% Fixed-Rate Resettable Junior Subordinated Notes due 2053"),
                new TickerData("APOpA",
                        "Apollo Global Management, Inc. 6.75% Series A Mandatory Convertible Preferred Stock"),
                new TickerData("APP", "Applovin Corporation Class A Common Stock"),
                new TickerData("APPF", "AppFolio, Inc. Class A"),
                new TickerData("APPN", "Appian Corporation Class A Common Stock"),
                new TickerData("APPS", "Digital Turbine, Inc."),
                new TickerData("APPX", "Tradr 2X Long APP Daily ETF"),
                new TickerData("APRE", "Aprea Therapeutics, Inc. Common stock"),
                new TickerData("APRH", "Innovator Premium Income 20 Barrier ETF - April"),
                new TickerData("APRJ", "Innovator Premium Income 30 Barrier ETF - April"),
                new TickerData("APRP", "PGIM S&P 500 Buffer 12 ETF - April"),
                new TickerData("APRT", "AllianzIM U.S. Large Cap Buffer10 Apr ETF"),
                new TickerData("APRW", "AllianzIM U.S. Large Cap Buffer20 Apr ETF"),
                new TickerData("APRZ", "TrueShares Structured Outcome (April) ETF"),
                new TickerData("APT", "Alpha Pro Tech, Ltd."),
                new TickerData("APTV", "Aptiv PLC"),
                new TickerData("APUE", "ActivePassive U.S. Equity ETF"),
                new TickerData("APUS", "Apimeds Pharmaceuticals US, Inc."),
                new TickerData("APVO", "Aptevo Therapeutics Inc"),
                new TickerData("APWC", "Asia Pacific Wire & Cable Corp"),
                new TickerData("APXM", "FT Vest U.S. Equity Max Buffer ETF - April"),
                new TickerData("APYX", "Apyx Medical Corporation Common Stock"),
                new TickerData("AQB", "AquaBounty Technologies, Inc."),
                new TickerData("AQLT", "iShares MSCI Global Quality Factor ETF"),
                new TickerData("AQMS", "Aqua Metals, Inc. Common Stock"),
                new TickerData("AQN", "Algonquin Power & Utilities Corp"),
                new TickerData("AQNB",
                        "Algonquin Power & Utilities Corp. 6.20% Fixed-to-Floating Subordinated Notes Series 2019-A due July 1, 2079"),
                new TickerData("AQST", "Aquestive Therapeutics, Inc. Common Stock"),
                new TickerData("AQWA", "Global X Clean Water ETF"),
                new TickerData("AR", "ANTERO RESOURCES CORPORATION"),
                new TickerData("ARAI", "Arrive AI Inc. Common Stock"),
                new TickerData("ARAY", "Accuray Incorporated"),
                new TickerData("ARB", "AltShares Merger Arbitrage ETF"),
                new TickerData("ARBB", "ARB IOT Group Limited Ordinary Shares"),
                new TickerData("ARBE", "Arbe Robotics Ltd. Ordinary Shares"),
                new TickerData("ARBEW", "Arbe Robotics Ltd. Warrant"),
                new TickerData("ARBK", "Argo Blockchain plc American Depositary Shares"),
                new TickerData("ARBKL", "Argo Blockchain plc 8.75% Senior Notes due 2026"),
                new TickerData("ARCB", "ArcBest Corporation"),
                new TickerData("ARCC", "Ares Capital Corporation"),
                new TickerData("ARCM", "Arrow Reserve Capital Management ETF"),
                new TickerData("ARCO", "ARCOS DORADOS HOLDINGS INC."),
                new TickerData("ARCT", "Arcturus Therapeutics Holdings Inc. Common Stock"),
                new TickerData("ARDC", "ARES DYNAMIC CREDIT ALLOCATION FUND, INC."),
                new TickerData("ARDT", "Ardent Health Partners, Inc."),
                new TickerData("ARDX", "Ardelyx, Inc."),
                new TickerData("ARE", "Alexandria Real Estate Equities, Inc."),
                new TickerData("AREA", "Harbor AlphaEdge Next Generation REITs ETF"),
                new TickerData("AREB", "American Rebel Holdings, Inc. Common Stock"),
                new TickerData("AREBW", "American Rebel Holdings, Inc. Warrants"),
                new TickerData("AREC", "AMERICAN RESOURCES CORP"),
                new TickerData("AREN", "The Arena Group Holdings, Inc."),
                new TickerData("ARES", "Ares Management Corporation Class A Common Stock"),
                new TickerData("ARESpB",
                        "Ares Management Corporation 6.75% Series B Mandatory Convertible Preferred Stock"),
                new TickerData("ARGD", "Argo Group US, Inc. 6.500% Senior Notes due 2042"),
                new TickerData("ARGOpA",
                        "Argo Group International Holdings, Inc. Depositary Shares, Each Representing a 1/1,000th Interest in a 7.00% Resettable Fixed Rate Preference Share, Series A"),
                new TickerData("ARGT", "Global X MSCI Argentina ETF"),
                new TickerData("ARGT", "Global X MSCI Argentina ETF"),
                new TickerData("ARGX", "argenx SE American Depositary Shares"),
                new TickerData("ARHS", "Arhaus, Inc. Class A Common Stock"),
                new TickerData("ARI", "APOLLO COMMERCIAL REAL ESTATE FINANCE, INC."),
                new TickerData("ARIS", "Aris Water Solutions, Inc."),
                new TickerData("ARKA", "ARK 21Shares Active Bitcoin Futures Strategy ETF"),
                new TickerData("ARKB", "ARK 21Shares Bitcoin ETF"),
                new TickerData("ARKD", "ARK 21Shares Blockchain and Digital Economy Innovation ETF"),
                new TickerData("ARKF", "ARK Fintech Innovation ETF"),
                new TickerData("ARKG", "ARK Genomic Revolution ETF"),
                new TickerData("ARKK", "ARK Innovation ETF"),
                new TickerData("ARKO", "ARKO Corp. Common Stock"),
                new TickerData("ARKOW", "ARKO Corp. Warrant"),
                new TickerData("ARKQ", "ARK Autonomous Technology & Robotics ETF"),
                new TickerData("ARKR", "Ark Restaurants Corp"),
                new TickerData("ARKW", "ARK Next Generation Internet ETF"),
                new TickerData("ARKX", "ARK Space Exploration & Innovation ETF"),
                new TickerData("ARKX", "ARK Space Exploration & Innovation ETF"),
                new TickerData("ARKZ", "ARK 21Shares Active Ethereum Futures Strategy ETF"),
                new TickerData("ARL", "American Realty Investors, Inc."),
                new TickerData("ARLO", "Arlo Technologies, Inc."),
                new TickerData("ARLP", "Alliance Resource Partners LP"),
                new TickerData("ARLU", "AllianzIM U.S. Equity Buffer15 Uncapped Apr ETF"),
                new TickerData("ARM", "Arm Holdings plc American Depositary Shares"),
                new TickerData("ARMG", "Leverage Shares 2X Long ARM Daily ETF"),
                new TickerData("ARMH", "Arm Holdings PLC ADRhedged"),
                new TickerData("ARMK", "ARAMARK"),
                new TickerData("ARMN", "Aris Mining Corporation"),
                new TickerData("ARMP", "Armata Pharmaceuticals, Inc. Common Stock"),
                new TickerData("ARMU", "T-REX 2X Long ARM Daily Target ETF"),
                new TickerData("AROC", "Archrock Inc"),
                new TickerData("AROW", "Arrow Financial Corp"),
                new TickerData("ARP", "PMV Adaptive Risk Parity ETF"),
                new TickerData("ARQ", "Arq, Inc. Common Stock"),
                new TickerData("ARQQ", "Arqit Quantum Inc. Ordinary Shares"),
                new TickerData("ARQQW", "Arqit Quantum Inc. Warrants"),
                new TickerData("ARQT", "Arcutis Biotherapeutics, Inc. Common Stock"),
                new TickerData("ARR", "ARMOUR Residential REIT, Inc."),
                new TickerData("ARRY", "Array Technologies, Inc. Common Stock"),
                new TickerData("ARRpC",
                        "ARMOUR Residential REIT, Inc. 7.00% Series C Cumulative Redeemable Preferred Stock"),
                new TickerData("ARTL", "Artelo Biosciences, Inc. Common Stock"),
                new TickerData("ARTN.A", "ARTESIAN RES CORP CL-A"),
                new TickerData("ARTNA", "Artesian Resources Corp"),
                new TickerData("ARTV", "Artiva Biotherapeutics, Inc. Common Stock"),
                new TickerData("ARTW", "Arts-Way Manufacturing Co Inc"),
                new TickerData("ARTY", "iShares Future AI & Tech ETF"),
                new TickerData("ARVN", "Arvinas, Inc"),
                new TickerData("ARVR", "First Trust Indxx Metaverse ETF"),
                new TickerData("ARW", "Arrow Electronics, Inc."),
                new TickerData("ARWR", "Arrowhead Research Corporation"),
                new TickerData("AS", "Amer Sports, Inc."),
                new TickerData("ASA", "ASA GOLD AND PRECIOUS METALS LIMITED"),
                new TickerData("ASAN", "Asana, Inc. Class A Common Stock"),
                new TickerData("ASB", "Associated Banc-Corp"),
                new TickerData("ASBA", "Associated Banc-Corp 6.625% Fixed-Rate Reset Subordinated Notes due 2033"),
                new TickerData("ASBP", "Aspire Biopharma Holdings, Inc. Common Stock"),
                new TickerData("ASBPW", "Aspire Biopharma Holdings, Inc. Warrant"),
                new TickerData("ASBpE",
                        "Associated Banc-Corp Depositary Shares, each representing a 1/40th interest in a share of 5.875% Non-Cumulative Perpetual Preferred Stock, Series E"),
                new TickerData("ASBpF",
                        "Associated Banc-Corp Depositary Shares, each representing a 1/40th interest in a share of Associated Banc-Corp 5. 625% Non-Cumulative Perpetual Preferred Stock, Series F"),
                new TickerData("ASC", "ARDMORE SHIPPING CORPORATION"),
                new TickerData("ASEA", "Global X FTSE Southeast Asia ETF"),
                new TickerData("ASEA", "Global X FTSE Southeast Asia ETF"),
                new TickerData("ASET", "FlexShares Real Assets Allocation Index Fund"),
                new TickerData("ASG", "LIBERTY ALL-STAR GROWTH FD"),
                new TickerData("ASGI", "abrdn Global Infrastructure Income Fund"),
                new TickerData("ASGN", "ASGN Incorporated"),
                new TickerData("ASH", "Ashland Inc."),
                new TickerData("ASHR", "Xtrackers Harvest CSI 300 China A-Shares ETF"),
                new TickerData("ASHS", "Xtrackers Harvest CSI 500 China A-Shares Small Cap ETF"),
                new TickerData("ASIA", "Matthews Pacific Tiger Active ETF"),
                new TickerData("ASIX", "AdvanSix Inc."),
                new TickerData("ASLE", "AerSale Corporation Common Stock"),
                new TickerData("ASLV", "Allspring Special Large Value ETF"),
                new TickerData("ASM", "Avino Silver & Gold Mines Ltd. (Canada)"),
                new TickerData("ASMB", "Assembly Biosciences, Inc"),
                new TickerData("ASMF", "Virtus AlphaSimplex Managed Futures ETF"),
                new TickerData("ASMG", "Leverage Shares 2X Long ASML Daily ETF"),
                new TickerData("ASMH", "ASML Holding NV ADRhedged"),
                new TickerData("ASML", "ASML Holding NV"),
                new TickerData("ASND", "Ascendis Pharma A/S American Depositary Shares"),
                new TickerData("ASNS", "Actelis Networks, Inc. Common Stock"),
                new TickerData("ASO", "Academy Sports and Outdoors, Inc."),
                new TickerData("ASPC", "A SPAC III Acquisition Corp. Class A Ordinary Shares"),
                new TickerData("ASPCR", "A SPAC III Acquisition Corp. Right"),
                new TickerData("ASPCU", "A SPAC III Acquisition Corp. Unit"),
                new TickerData("ASPI", "ASP Isotopes Inc. Common Stock"),
                new TickerData("ASPN", "Aspen Aerogels, Inc."),
                new TickerData("ASPS", "Altisource Portfolio Solutions S.A."),
                new TickerData("ASPSW", "Altisource Portfolio Solutions S.A. Net Settle Stakeholder Warrants"),
                new TickerData("ASPSZ", "Altisource Portfolio Solutions S.A. Cash Exercise Stakeholder Warrants"),
                new TickerData("ASR", "Grupo Aeroportuario del Sureste, S.A. de C.V. American Depositary Shares"),
                new TickerData("ASRT", "Assertio Holdings, Inc. Common Stock"),
                new TickerData("ASRV", "AmeriServ Financial Inc"),
                new TickerData("ASST", "Asset Entities Inc. Class B Common Stock"),
                new TickerData("ASTC", "Astrotech Corporation (DE) Common Stock"),
                new TickerData("ASTE", "Astec Industries Inc"),
                new TickerData("ASTH", "Astrana Health Inc. Common Stock"),
                new TickerData("ASTI", "Ascent Solar Technologies, Inc. Common Stock"),
                new TickerData("ASTL", "Algoma Steel Group Inc. Common Shares"),
                new TickerData("ASTLW", "Algoma Steel Group Inc. Warrant"),
                new TickerData("ASTS", "AST SpaceMobile, Inc. Class A Common Stock"),
                new TickerData("ASUR", "Asure Software, Inc"),
                new TickerData("ASX", "ASE Technology Holding Co., Ltd."),
                new TickerData("ASYS", "Amtech Systems Inc"),
                new TickerData("ATAI", "ATAI Life Sciences N.V. Common Shares"),
                new TickerData("ATAT", "Atour Lifestyle Holdings Limited American Depositary Shares"),
                new TickerData("ATCH", "AtlasClear Holdings, Inc."),
                new TickerData("ATCOL", "Atlas Corp. 7.125% Notes due 2027"),
                new TickerData("ATCOpD", "Atlas Corp. 7.95% Series D Cumulative Redeemable Perpetual Preferred Shares"),
                new TickerData("ATCOpH",
                        "Atlas Corp. 7.875% Cumulative Redeemable Perpetual Preferred Shares - Series H"),
                new TickerData("ATEC", "Alphatec Holdings, Inc."),
                new TickerData("ATEN", "A10 NETWORKS INC"),
                new TickerData("ATER", "Aterian, Inc. Common Stock"),
                new TickerData("ATEX", "Anterix Inc. Common Stock"),
                new TickerData("ATFV", "Alger 35 ETF"),
                new TickerData("ATGE", "Adtalem Global Education Inc. Common Shares"),
                new TickerData("ATGL", "Alpha Technology Group Limited Class A Ordinary Shares"),
                new TickerData("ATHA", "Athira Pharma, Inc. Common Stock"),
                new TickerData("ATHE", "Alterity Therapeutics Limited American Depositary Shares"),
                new TickerData("ATHM",
                        "Autohome Inc. American Depositary Shares, each representing four Class A Ordinary Shares"),
                new TickerData("ATHR", "Aether Holdings, Inc. Common Stock"),
                new TickerData("ATHS",
                        "Athene Holding Ltd. 7.250% Fixed-Rate Reset Junior Subordinated Debentures due 2064"),
                new TickerData("ATHpA",
                        "Athene Holding Ltd. Depositary Shares, Each Representing a 1/1,000th Interest in a 6.35% Fixed-to-Floating Rate Perpetual Non-Cumulative Preference Share, Series A"),
                new TickerData("ATHpB",
                        "Athene Holding Ltd. Depositary Shares, Each Representing a 1/1,000th Interest in a 5.625% Fixed Rate Perpetual Non- Cumulative Preference Share, Series B, par value $1.00 per share"),
                new TickerData("ATHpC",
                        "Athene Holding Ltd. Depositary Shares, each representing a 1/1, 000th Interest in a Share of 6.375% Fixed-Rate Reset Perpetual Non-Cumulative Preference Shares, Series C"),
                new TickerData("ATHpD",
                        "Athene Holding Ltd. Depositary Shares, Each Representing a 1/1,000th Interest in a 4.875% Fixed-Rate Perpetual Non-Cumulative Preference Share, Series D"),
                new TickerData("ATHpE",
                        "Athene Holding Ltd. Depositary Shares, Each Representing a 1/1,000th Interest in a 7.750% Fixed-Rate Reset Perpetual Non-Cumulative Preference Share, Series E"),
                new TickerData("ATI", "ATI Inc."),
                new TickerData("ATII", "Archimedes Tech SPAC Partners II Co. Ordinary Shares"),
                new TickerData("ATIIU", "Archimedes Tech SPAC Partners II Co. Unit"),
                new TickerData("ATIIW", "Archimedes Tech SPAC Partners II Co. Warrant"),
                new TickerData("ATKR", "Atkore Inc."),
                new TickerData("ATLC", "Atlanticus Holdings Corporation"),
                new TickerData("ATLCL", "Atlanticus Holdings Corporation 6.125% Senior Notes due 2026"),
                new TickerData("ATLCP",
                        "Atlanticus Holdings Corporation 7.625% Series B Cumulative Perpetual Preferred Stock, no par value per share"),
                new TickerData("ATLCZ", "Atlanticus Holdings Corporation 9.25% Senior Notes due 2029"),
                new TickerData("ATLN", "Atlantic International Corp. Common Stock"),
                new TickerData("ATLO", "AMES National Corp"),
                new TickerData("ATLX", "Atlas Lithium Corporation Common Stock"),
                new TickerData("ATMC", "AlphaTime Acquisition Corp Ordinary Shares"),
                new TickerData("ATMCR", "AlphaTime Acquisition Corp Right"),
                new TickerData("ATMCU", "AlphaTime Acquisition Corp Unit"),
                new TickerData("ATMCW", "AlphaTime Acquisition Corp Warrant"),
                new TickerData("ATMP", "iPath Select MLP ETN"),
                new TickerData("ATMP", "iPath Select MLP ETN"),
                new TickerData("ATMU", "Atmus Filtration Technologies Inc."),
                new TickerData("ATMV", "AlphaVest Acquisition Corp Ordinary Shares"),
                new TickerData("ATMVR", "AlphaVest Acquisition Corp Right"),
                new TickerData("ATMVU", "AlphaVest Acquisition Corp Unit"),
                new TickerData("ATNF", "180 Life Sciences Corp. Common Stock"),
                new TickerData("ATNFW", "180 Life Sciences Corp. Warrant"),
                new TickerData("ATNI", "ATN International, Inc"),
                new TickerData("ATNM", "Actinium Pharmaceuticals, Inc"),
                new TickerData("ATO", "Atmos Energy Corporation"),
                new TickerData("ATOM", "Atomera Incorporated Common Stock"),
                new TickerData("ATOS", "Atossa Therapeutics, Inc. Common Stock"),
                new TickerData("ATPC", "Agape ATP Corporation Common Stock"),
                new TickerData("ATR", "AptarGroup, Inc."),
                new TickerData("ATRA", "Atara Biotherapeutics, Inc"),
                new TickerData("ATRC", "AtriCure, Inc."),
                new TickerData("ATRO", "Astronics Corp"),
                new TickerData("ATS", "ATS Corporation"),
                new TickerData("ATUS", "Altice USA, Inc. Class A Common Stock"),
                new TickerData("ATXG", "Addentax Group Corp. Common Stock"),
                new TickerData("ATXS", "Astria Therapeutics, Inc. Common Stock"),
                new TickerData("ATYR", "aTyr Pharma, Inc. Common Stock"),
                new TickerData("AU", "AngloGold Ashanti plc"),
                new TickerData("AUB", "Atlantic Union Bankshares Corporation"),
                new TickerData("AUBN", "Auburn National Bancorporation"),
                new TickerData("AUBpA",
                        "Atlantic Union Bankshares Corporation Depositary Shares, Each Representing a 1/400th Interest in a Share of 6.875% Perpetual Non-Cumulative Preferred Stock, Series A"),
                new TickerData("AUDC", "AudioCodes Ltd"),
                new TickerData("AUGM", "FT Vest U.S. Equity Max Buffer ETF - August"),
                new TickerData("AUGP", "PGIM S&P 500 Buffer 12 ETF - August"),
                new TickerData("AUGT", "AllianzIM U.S. Large Cap Buffer10 Aug ETF"),
                new TickerData("AUGU", "AllianzIM U.S. Equity Buffer15 Uncapped Aug ETF"),
                new TickerData("AUGW", "AllianzIM U.S. Large Cap Buffer20 Aug ETF"),
                new TickerData("AUGZ", "TrueShares Structured Outcome (August) ETF"),
                new TickerData("AUID", "authID Inc. Common Stock"),
                new TickerData("AUMI", "Themes Gold Miners ETF"),
                new TickerData("AUNA", "Auna S.A."),
                new TickerData("AUPH", "Aurinia Pharmaceuticals Inc"),
                new TickerData("AUR", "Aurora Innovation, Inc. Class A Common Stock"),
                new TickerData("AURA", "Aura Biosciences, Inc. Common Stock"),
                new TickerData("AUROW", "Aurora Innovation, Inc. Warrant"),
                new TickerData("AUSF", "Global X Adaptive U.S. Factor ETF"),
                new TickerData("AUST", "Austin Gold Corp."),
                new TickerData("AUTL", "Autolus Therapeutics plc American Depositary Share"),
                new TickerData("AUUD", "Auddia Inc. Common Stock"),
                new TickerData("AUUDW", "Auddia Inc. Warrants"),
                new TickerData("AVA", "Avista Corporation"),
                new TickerData("AVAH", "Aveanna Healthcare Holdings Inc. Common Stock"),
                new TickerData("AVAL", "GRUPO AVAL ACCIONES Y VALORES S.A."),
                new TickerData("AVAV", "AeroVironment, Inc."),
                new TickerData("AVB", "AvalonBay Communities, Inc."),
                new TickerData("AVBP", "ArriVent BioPharma, Inc. Common Stock"),
                new TickerData("AVD", "American Vanguard Corporation"),
                new TickerData("AVDE", "Avantis International Equity ETF"),
                new TickerData("AVDL", "Avadel Pharmaceuticals plc Ordinary Share"),
                new TickerData("AVDS", "Avantis International Small Cap Equity ETF"),
                new TickerData("AVDV", "Avantis International Small Cap Value ETF"),
                new TickerData("AVDX", "AvidXchange Holdings, Inc. Common Stock"),
                new TickerData("AVEE", "Avantis Emerging Markets Small Cap Equity ETF"),
                new TickerData("AVEM", "Avantis Emerging Markets Equity ETF"),
                new TickerData("AVES", "Avantis Emerging Markets Value ETF"),
                new TickerData("AVGB", "Avantis Credit ETF"),
                new TickerData("AVGE", "Avantis All Equity Markets ETF"),
                new TickerData("AVGG", "Leverage Shares 2X Long AVGO Daily ETF"),
                new TickerData("AVGO", "Broadcom Inc. Common Stock"),
                new TickerData("AVGV", "Avantis All Equity Markets Value ETF"),
                new TickerData("AVGX", "Defiance Daily Target 2X Long AVGO ETF"),
                new TickerData("AVIE", "Avantis Inflation Focused Equity ETF"),
                new TickerData("AVIG", "Avantis Core Fixed Income ETF"),
                new TickerData("AVIR", "Atea Pharmaceuticals, Inc. Common Stock"),
                new TickerData("AVIV", "Avantis International Large Cap Value ETF"),
                new TickerData("AVK", "Advent Convertible and Income Fund"),
                new TickerData("AVL", "Direxion Daily AVGO Bull 2X Shares"),
                new TickerData("AVLC", "Avantis U.S. Large Cap Equity ETF"),
                new TickerData("AVLV", "Avantis U.S. Large Cap Value ETF"),
                new TickerData("AVMA", "Avantis Moderate Allocation ETF"),
                new TickerData("AVMC", "Avantis U.S. Mid Cap Equity ETF"),
                new TickerData("AVMU", "Avantis Core Municipal Fixed Income ETF"),
                new TickerData("AVMV", "Avantis U.S. Mid Cap Value ETF"),
                new TickerData("AVNM", "Avantis All International Markets Equity ETF"),
                new TickerData("AVNS", "Avanos Medical, Inc."),
                new TickerData("AVNT", "Avient Corporation"),
                new TickerData("AVNV", "Avantis All International Markets Value ETF"),
                new TickerData("AVNW", "Aviat Networks, Inc."),
                new TickerData("AVO", "Mission Produce, Inc. Common Stock"),
                new TickerData("AVPT", "AvePoint, Inc. Class A Common Stock"),
                new TickerData("AVPTW", "AvePoint, Inc. Warrant"),
                new TickerData("AVR", "Anteris Technologies Global Corp. Common Stock"),
                new TickerData("AVRE", "Avantis Real Estate ETF"),
                new TickerData("AVS", "Direxion Daily AVGO Bear 1X Shares"),
                new TickerData("AVSC", "Avantis U.S. Small Cap Equity ETF"),
                new TickerData("AVSD", "Avantis Responsible International Equity ETF"),
                new TickerData("AVSE", "Avantis Responsible Emerging Markets Equity ETF"),
                new TickerData("AVSF", "Avantis Short-Term Fixed Income ETF"),
                new TickerData("AVSU", "Avantis Responsible U.S. Equity ETF"),
                new TickerData("AVT", "Avnet, Inc."),
                new TickerData("AVTR", "Avantor, Inc."),
                new TickerData("AVTX", "Avalo Therapeutics, Inc. Common Stock"),
                new TickerData("AVUQ", "Avantis U.S. Quality ETF"),
                new TickerData("AVUS", "Avantis U.S. Equity ETF"),
                new TickerData("AVUV", "Avantis U.S. Small Cap Value ETF"),
                new TickerData("AVXC", "Avantis Emerging Markets ex-China Equity ETF"),
                new TickerData("AVXL", "Anavex Life Sciences"),
                new TickerData("AVY", "Avery Dennison Corp."),
                new TickerData("AWAY", "Amplify Travel Tech ETF"),
                new TickerData("AWEG", "Alger Weatherbie Enduring Growth ETF"),
                new TickerData("AWF", "ALLIANCEBERSTEIN GLOBAL HIGH INCOME FUND, INC."),
                new TickerData("AWI", "Armstrong World Industries, Inc."),
                new TickerData("AWK", "American Water Works Company, Inc"),
                new TickerData("AWP", "abrdn Global Premier Properties Fund"),
                new TickerData("AWR", "American States Water Company"),
                new TickerData("AWRE", "Aware Inc"),
                new TickerData("AWX", "Avalon Holdings Corp."),
                new TickerData("AX", "Axos Financial, Inc. Common Stock"),
                new TickerData("AXGN", "Axogen, Inc. Common Stock"),
                new TickerData("AXIL", "AXIL Brands, Inc."),
                new TickerData("AXL", "American Axle & Manufacturing Holdings, Inc."),
                new TickerData("AXON", "Axon Enterprise, Inc. Common Stock"),
                new TickerData("AXP", "American Express Company"),
                new TickerData("AXR", "AMREP Corporation"),
                new TickerData("AXS", "Axis Capital Holders Limited"),
                new TickerData("AXSM", "Axsome Therapeutics, Inc"),
                new TickerData("AXSpE",
                        "AXIS Capital Holdings Limited Depositary Shares, each representing 1/100th interest in a share of the Issuers 5.50% Series E Preferred Shares"),
                new TickerData("AXTA", "Axalta Coating Systems Ltd."),
                new TickerData("AXTI", "AXT Inc"),
                new TickerData("AYI", "Acuity Inc."),
                new TickerData("AYRO", "AYRO, Inc. Common Stock"),
                new TickerData("AYTU", "AYTU BioPharma, Inc. Common Stock"),
                new TickerData("AZ", "A2Z Cust2Mate Solutions Corp. Common Shares"),
                new TickerData("AZEK", "The AZEK Company Inc."),
                new TickerData("AZI", "Autozi Internet Technology (Global) Ltd. Class A Ordinary Shares"),
                new TickerData("AZN", "AstraZeneca PLC"),
                new TickerData("AZNH", "AstraZeneca PLC ADRhedged"),
                new TickerData("AZO", "AutoZone, Inc."),
                new TickerData("AZTA", "Azenta, Inc."),
                new TickerData("AZTD", "Aztlan Global Stock Selection DM SMID ETF"),
                new TickerData("AZTR", "Azitra Inc"),
                new TickerData("AZUL",
                        "Azul S.A. American Depositary Shares (each representing three preferred shares)"),
                new TickerData("AZZ", "AZZ Inc."),
                new TickerData("B", "Barrick Mining Corporation"),
                new TickerData("BA", "Boeing Company"),
                new TickerData("BAB", "Invesco Taxable Municipal Bond ETF"),
                new TickerData("BABA",
                        "Alibaba Group Holding Limited American Depositary Shares, each represents eight Ordinary Shares"),
                new TickerData("BABO", "YieldMax BABA Option Income Strategy ETF"),
                new TickerData("BABX", "GraniteShares ETF Trust GraniteShares 2x Long BABA Daily ETF"),
                new TickerData("BAC", "Bank of America Corporation"),
                new TickerData("BACQ", "Bleichroeder Acquisition Corp. I Class A Ordinary Shares"),
                new TickerData("BACQR", "Bleichroeder Acquisition Corp. I Right"),
                new TickerData("BACQU", "Bleichroeder Acquisition Corp. I Unit"),
                new TickerData("BACpB",
                        "Bank of America Corporation Depositary Shares, each representing a 1/1,000th interest in a share of 6.000% Non-Cumulative Preferred Stock, Series GG"),
                new TickerData("BACpE",
                        "Bank of America Corporation Depositary Shares (representing 1/1,000th of a share of Floating Rate Non-Cumalative Preferred Stock, Series E)"),
                new TickerData("BACpK",
                        "Bank of America Corporation Depositary Shares, each representing a 1/1,000th interest in a share of 5.875% Non- Cumulative Preferred Stock, Series HH"),
                new TickerData("BACpL",
                        "Bank Of America Corporation 7.25% Non-Cumulative Perpetual Convertible Preferred Stock, Series L"),
                new TickerData("BACpM",
                        "Bank of America Corporation Depositary Shares, each representing a 1/1,000th interest in a share of 5.375% Non-Cumulative Preferred Stock, Series KK"),
                new TickerData("BACpN",
                        "Bank of America Corporation Depositary shares, each representing 1/1,000th interest in a share of 5.000% Non-Cumulative Preferred Stock, Series LL"),
                new TickerData("BACpO",
                        "Bank of America Corporation Depositary shares, each representing 1/1,000th interest in a share of 4.375% Non-Cumulative Preferred Stock, Series NN"),
                new TickerData("BACpP",
                        "Bank of America Corporation Depositary Shares, each representing a 1/1,000th interest in a share of 4.125% Non- Cumulative Preferred Stock, Series PP"),
                new TickerData("BACpQ",
                        "Bank of America Corporation Depositary shares, each representing 1/1,000th interest in a share of 4.250% Non-Cumulative Preferred Stock, Series QQ"),
                new TickerData("BACpS",
                        "Bank of America Corporation Depositary shares, each representing 1/1,000th interest in a share of 4.750% Non-Cumulative Preferred Stock, Series SS"),
                new TickerData("BAER", "Bridger Aerospace Group Holdings, Inc. Common Stock"),
                new TickerData("BAERW", "Bridger Aerospace Group Holdings, Inc. Warrant"),
                new TickerData("BAFE", "Brown Advisory Flexible Equity ETF"),
                new TickerData("BAFN", "BayFirst Financial Corp. Common Stock"),
                new TickerData("BAGY", "Amplify Bitcoin Max Income Covered Call ETF"),
                new TickerData("BAH", "Booz Allen Hamilton Holding Corporation"),
                new TickerData("BAI", "iShares A.I. Innovation and Tech Active ETF"),
                new TickerData("BAK",
                        "Braskem S.A. American Depositary Shares (Each representing Two Class A  Preferred Shares)"),
                new TickerData("BALI", "iShares Advantage Large Cap Income ETF"),
                new TickerData("BALL", "Ball Corporation"),
                new TickerData("BALT", "Innovator Defined Wealth Shield ETF"),
                new TickerData("BALY", "Bally's Corporation"),
                new TickerData("BAM", "Brookfield Asset Management Ltd."),
                new TickerData("BAMA", "Brookstone Active ETF"),
                new TickerData("BAMB", "Brookstone Intermediate Bond ETF"),
                new TickerData("BAMD", "Brookstone Dividend Stock ETF"),
                new TickerData("BAMG", "Brookstone Growth Stock ETF"),
                new TickerData("BAMO", "Brookstone Opportunities ETF"),
                new TickerData("BAMU", "Brookstone Ultra-Short Bond ETF"),
                new TickerData("BAMV", "Brookstone Value Stock ETF"),
                new TickerData("BAMY", "Brookstone Yield ETF"),
                new TickerData("BANC", "Banc of California, Inc."),
                new TickerData("BANCpF",
                        "Banc of California, Inc. Depositary Shares, each representing a 1/40th interest in a share of 7.75% non- cumulative perpetual preferred stock, Series F"),
                new TickerData("BAND", "Bandwidth Inc. Class A Common Stock"),
                new TickerData("BANF", "Bancfirst Corp"),
                new TickerData("BANFP", "BancFirst Corporation - BFC Capital Trust II Cumulative Trust Pfd Secs"),
                new TickerData("BANL", "CBL International Limited Ordinary Shares"),
                new TickerData("BANR", "Banner Corp."),
                new TickerData("BANX", "ArrowMark Financial Corp. Common Stock"),
                new TickerData("BAOS", "Baosheng Media Group Holdings Limited Ordinary shares"),
                new TickerData("BAP", "Credicorp LTD"),
                new TickerData("BAPR", "Innovator U.S. Equity Buffer ETF - April"),
                new TickerData("BAR", "GraniteShares Gold Shares"),
                new TickerData("BARK", "BARK, Inc."),
                new TickerData("BARK.WS",
                        "BARK, Inc. Redeemable Warrants, each whole warrant exercisable for shares of Common Stock at an exercise price of $11.50 per share"),
                new TickerData("BASE", "Couchbase, Inc. Common Stock"),
                new TickerData("BATL", "Battalion Oil Corporation"),
                new TickerData("BATRA", "Atlanta Braves Holdings, Inc. Series A Common Stock"),
                new TickerData("BATRK", "Atlanta Braves Holdings, Inc. Series C Common Stock"),
                new TickerData("BATT", "Amplify Lithium & Battery Technology ETF"),
                new TickerData("BAUG", "Innovator U.S. Equity Buffer ETF - August"),
                new TickerData("BAX", "Baxter International Inc."),
                new TickerData("BAYA", "Bayview Acquisition Corp Class A Ordinary Shares"),
                new TickerData("BAYAR", "Bayview Acquisition Corp Right"),
                new TickerData("BAYAU", "Bayview Acquisition Corp Unit"),
                new TickerData("BApA",
                        "The Boeing Company Depositary Shares, each representing a 1/20th interest in a share of 6.00% Series A Mandatory Convertible Preferred Stock, par value $1.00"),
                new TickerData("BB", "BlackBerry Limited"),
                new TickerData("BBAG", "JPMorgan BetaBuilders U.S. Aggregate Bond ETF"),
                new TickerData("BBAI", "BigBear.ai Holdings, Inc."),
                new TickerData("BBAI.WS",
                        "BigBear.ai Holdings, Inc. Redeemable warrants, each full warrant exercisable for one share of common stock at an exercise price of $11.50 per share"),
                new TickerData("BBAR", "Banco BBVA Argentina S.A."),
                new TickerData("BBAX", "JPMorgan BetaBuilders Developed Asia Pacific-ex Japan ETF"),
                new TickerData("BBBI", "BondBloxx BBB Rated 5-10 Year Corporate Bond ETF"),
                new TickerData("BBBL", "BondBloxx BBB Rated 10+ Year Corporate Bond ETF"),
                new TickerData("BBBS", "BondBloxx BBB Rated 1-5 Year Corporate Bond ETF"),
                new TickerData("BBC", "Virtus LifeSci Biotech Clinical Trials ETF"),
                new TickerData("BBCA", "JPMorgan BetaBuilders Canada ETF"),
                new TickerData("BBCB", "JPMorgan BetaBuilders USD Investment Grade Corporate Bond ETF"),
                new TickerData("BBCP", "Concrete Pumping Holdings, Inc. Common Stock"),
                new TickerData("BBD",
                        "Banco Bradesco S.A. American Depositary Shares (Each representing one Preferred Shares)"),
                new TickerData("BBDC", "Barings BDC, Inc."),
                new TickerData("BBDO",
                        "Banco Bradesco S.A. American Depositary Shares (Each representing one  Common Share, no par value)"),
                new TickerData("BBEM", "JPMorgan BetaBuilders Emerging Markets Equity ETF"),
                new TickerData("BBEU", "JPMorgan BetaBuilders Europe ETF"),
                new TickerData("BBGI", "Beasley Broadcasting Group Inc"),
                new TickerData("BBH", "VanEck Biotech ETF"),
                new TickerData("BBI", "B2Gold Corp."),
                new TickerData("BBIO", "BridgeBio Pharma, Inc. Common Stock"),
                new TickerData("BBIOW", "BridgeBio Pharma, Inc. Warrant"),
                new TickerData("BBK", "BlackRock Municipal Income Trust"),
                new TickerData("BBL", "BHP Billiton Limited"),
                new TickerData("BBLG", "BlackRock Municipal Income Trust II"),
                new TickerData("BBLU", "BlackRock Municipal Income Trust III"),
                new TickerData("BBMC", "BlackRock Municipal Income Trust IV"),
                new TickerData("BBN", "BlackRock Taxable Municipal Bond Trust"),
                new TickerData("BBP", "BlackRock Municipal Income Trust"),
                new TickerData("BBQ", "BBQ Holdings, Inc."),
                new TickerData("BBQ.WS",
                        "BBQ Holdings, Inc. Redeemable Warrants, each whole warrant exercisable for one share of Common Stock at an exercise price of $11.50 per share"),
                new TickerData("BBRA", "JPMorgan BetaBuilders Brazil ETF"),
                new TickerData("BBSA", "JPMorgan BetaBuilders Asia ex-Japan ETF"),
                new TickerData("BBSD", "BlackRock Municipal Income Trust II"),
                new TickerData("BBT", "Truist Financial Corporation"),
                new TickerData("BBTC", "BitBull Capital"),
                new TickerData("BBU", "Brookfield Business Partners L.P."),
                new TickerData("BBUC",
                        "Brookfield Business Partners L.P. 5.75% Series A Cumulative Redeemable Preferred Shares"),
                new TickerData("BBUS", "BlackRock U.S. Equity Factor Rotation ETF"));

                return list;
    }
}
